---
title: "CoLiPhi21"
include: ["./practice_lessons/lesson_1/src/session_1v1.Rmd", "./practice_lessons/lesson_2/src/session_2v1.Rmd", "./create_corpora/src/pres_philpeople.Rmd", "./create_corpora/src/pres_make_corpus.Rmd", "./create_corpora/src/pres_standfordEnc.Rmd", "./practice_lessons/lesson_3/pres.Rmd", "./practice_lessons/mark/1st/Nietzschescripts.Rmd"]
output_dir: "docs"
output: html_document
---

## Corpus Linhuistics and Philosophy Workshop 21

Hi! This is the online repository for CoLiPhi21:

- Mark Alfano I - Nietzsche Corpus Analysis:
  - [Presentation](./practice_lessons/mark/1st/Nietzschescripts.html)
  - [Code](./practice_lessons/mark/1st/Nietzschescripts.Rmd)
  - [Data](./practice_lessons/mark/1st/data/nietzsche.zip)
<br>  

- Mark Alfano II - BLM:
  - [Presentation](./practice_lessons/mark/2nd/BLMscripts.html)
  - [Code](./practice_lessons/mark/2nd/BLMscripts.Rmd)
  - [Data](./practice_lessons/mark/2nd/data/blm.zip)
<br>

- Justin Sytsma I - Corpus Methods and Experimental Philosophy:
  - [Presentation](./practice_lessons/mark/2nd/Corpus Methods and Experimental Philosophy.pdf)
<br>  

- Justin Sytsma II - Causal Attributions and Corpus Analysis:
  - [Presentation](./practice_lessons/mark/2nd/Causal Attributions and Corpus Analysis.pdf)
  - [Data](./practice_lessons/mark/2nd/data/causal_attribution.zip)
<br>

- Lucien Baumgartner I - The Quanteda-Suite:
  - [Presentation](./practice_lessons/lesson_1/src/session_1v1.html)
  - [Code](./practice_lessons/lesson_1/src/session_1v1.Rmd)
<br>

- Lucien Baumgartner II - Inductive Analytics:
  - [Presentation](./practice_lessons/lesson_2/src/session_2v1.html)
  - [Code](./practice_lessons/lesson_2/src/session_2v1.Rmd)
  - [Data](./practice_lessons/lesson_2/src/session_2v1.)
<br>

- Lucien Baumgartner III - Text Mining:
  - [Presentation](./practice_lessons/lesson_3/pres.html)
  - [Code](./create_corpora/src/text_mining.zip)
  

